language: python
python:
  - "3.6"
install:
  - pip install flake8
  - pip install -r requirements.txt
before_script: flake8  --statistics --ignore=E501,W291,W293
script: python test/test_api.py
branches:
  only:
    - master