language: python
python:
  - "3.6"
install:
  - pip install flake8 --ignore=E501,W291,W293
  - pip install -r requirements.txt
before_script: flake8
script: python test/test_api.py
branches:
  only:
    - master